institutionFrontend/.gitignore
institutionFrontend/src/auth/LoginForm.jsx

Login page created.
.env file gitignored

#2 login page created, integrating with backend pending, .env gitignored by anaz

---

institutionFrontend/src/auth/LoginForm.jsx
institutionFrontend/src/auth/SignupForm.jsx

add navigation option bw  login and signup page

#3v1 update SingUp page and Login Page  by saeed NM

---

institutionFrontend/eslint.config.js
institutionFrontend/package-lock.json
institutionFrontend/package.json
institutionFrontend/src/App.jsx
institutionFrontend/src/auth/LoginForm.jsx
institutionFrontend/src/auth/SignupForm.jsx
institutionFrontend/src/component/Otp/OtpInput.jsx
institutionFrontend/src/component/Skeletons/OtpSkeleton.jsx
institutionFrontend/src/hooks/useToast.jsx
institutionFrontend/src/services/user/LoginServices.jsx
institutionFrontend/src/services/user/SignupServices.jsx
institutionFrontend/src/utils/axios.jsx
institutionFrontend/tailwind.config.js

1. Complete signup page functionalitty with backend 
2 .Complete OTP component with validation 
3 . Complete OTP Skeleton 
4 . Add new Custome Hook for Message name is "useToast" it take two args one is message and second one is type like success or error 
5 . setup axios 
6 . add navigation form successfull signup

#9 completed signup otp verifications with backend by saeed

---

institutionFrontend/src/auth/SignupForm.jsx

update otp error message display by saeed

#9v1 update otp error message display by saeed

---

institutionFrontend/src/auth/LoginForm.jsx
institutionFrontend/src/hooks/useToast.jsx
institutionFrontend/src/services/user/LoginServices.jsx

login page integrated with backend
attempt
Invalid inputs
Success login directed to home page

#11 login page integrated with backend, google signin pending. by anaz

---

institutionFrontend/.env
institutionFrontend/src/auth/GoogleSignIn.jsx
institutionFrontend/src/services/GoogleSignInServices.jsx

google sign in integrated with backend by Anaz. To be tested with backend and modification needed to be added.

#13 google sign in integrated with backend by Anaz.

---

institutionFrontend/src/auth/GoogleSignIn.jsx
institutionFrontend/src/services/GoogleSignInServices.jsx

To avoid any possible conflict with backend...the 'token' is changed to 'access_token'

#13v1 token name changed to access_token for google sign in services

---

institutionFrontend/src/component/Card/Card.jsx
institutionFrontend/src/component/Footer/Footer.jsx
institutionFrontend/src/component/Navbar/Navbar.jsx
institutionFrontend/src/component/Newcourses/Newcourses.jsx
institutionFrontend/src/component/PageNotFound/PageNotFound.jsx
institutionFrontend/src/component/Popularcourses/Popularcourse.jsx
institutionFrontend/src/component/ProgramDetail/ProgramDetail.jsx
institutionFrontend/src/component/Programs/Programs.jsx
institutionFrontend/src/pages/user/Home.jsx
institutionFrontend/src/pages/user/ProgramDetailPage.jsx
institutionFrontend/src/pages/user/ProgramPage.jsx
institutionFrontend/src/routes/user/UserRoutes.jsx

#23 programs list page and program detail page created. Backend integration pending. by Anaz

---

institutionFrontend/src/component/Newcourses/Newcourses.jsx
institutionFrontend/src/component/Popularcourses/Popularcourse.jsx
institutionFrontend/src/services/courses/FetchLatestCourses.jsx

Api for fetching latest course
use effect to fetch latest course...
Note: Popular course also temporarly uswed this use effect...separate api to be created for it later.

#35 API created for fetching latest course from backend, popular course pending. by Anaz

---

institutionFrontend/src/component/ProgramDetail/ProgramDetail.jsx
institutionFrontend/src/services/courses/FetchLatestCourses.jsx
institutionFrontend/src/services/courses/FetchProgramCourses.jsx
institutionFrontend/src/services/courses/FetchPrograms.jsx

also axios instance changed to noAuthInstance for these fetching data of courses and programs

#37 Api created to fetch course data of a pragram and displayed in the program detail page. by Anaz

---

institutionFrontend/package-lock.json
institutionFrontend/package.json
institutionFrontend/src/component/Profile/profile.jsx
institutionFrontend/src/component/Profile/styles.jsx
institutionFrontend/src/pages/user/userProfile.jsx

updated styles with styles.jsx to avoid single line styling

updated styles with styles.jsx to avoid single line styling

---

institutionFrontend/src/component/Modals/UserCrudModal.jsx
institutionFrontend/src/component/Tables/DataTable.jsx
institutionFrontend/src/component/ThemeProvider/ThemeProvider.jsx
institutionFrontend/src/pages/admin/CourseAdmin.jsx
institutionFrontend/src/pages/admin/Instructor.jsx
institutionFrontend/src/pages/admin/ShopeAdmin.jsx
institutionFrontend/src/pages/admin/Users.jsx

Updated Admin dashboard table style and Added Button for Creating Shope and Course Admin

Updated Admin dashboard table style and Added Button for Creating Shope and Course Admin  

---

institutionFrontend/src/component/Drawer/ProductFilter.jsx
institutionFrontend/src/pages/user/ProductsList.jsx

#103 initialized filter Drawer and set space for productCard

#103 initialized filter Drawer and set space for productCard

---

institutionFrontend/src/component/Drawer/ProductFilter.jsx
institutionFrontend/src/component/Drawer/styles.js
institutionFrontend/src/pages/user/ProductsList.jsx
institutionFrontend/src/services/user/ProductServices.jsx

#103v1 completed product filter page

#103v1 completed product filter page

---

institutionFrontend/src/component/Card/ProductCard.jsx
institutionFrontend/src/pages/user/ProductsList.jsx

#104v1  fix conflict by saeed

---

institutionFrontend/package-lock.json
institutionFrontend/package.json
institutionFrontend/src/component/Card/ProductCard.jsx
institutionFrontend/src/component/ProductImages/ProductImage.jsx
institutionFrontend/src/component/ProductImages/Style.js
institutionFrontend/src/pages/user/ecommerce/ProductDetailPage.jsx
institutionFrontend/src/routes/user/UserRoutes.jsx

created images detail  page by saeed nm

#109 created images detail  page by saeed nm

---

institutionFrontend/src/component/Breadcrumbs/Breadcrumbs.jsx
institutionFrontend/src/component/Button/BackButton.jsx
institutionFrontend/src/component/Card/Card.jsx
institutionFrontend/src/component/Modals/ConfirmModal.jsx
institutionFrontend/src/component/Modals/ConfirmationModalStyles.js
institutionFrontend/src/component/Navbar/Navbar.jsx
institutionFrontend/src/component/Profile/profile.jsx
institutionFrontend/src/component/Profile/styles.jsx
institutionFrontend/src/component/ProgramDetail/ProgramDetail.jsx
institutionFrontend/src/component/Programs/Programs.jsx
institutionFrontend/src/component/Tables/DataTable.jsx
institutionFrontend/src/component/Tables/TableColumns.jsx
institutionFrontend/src/pages/CourseAdmin/BatchForm.jsx
institutionFrontend/src/pages/CourseAdmin/Batches.jsx
institutionFrontend/src/pages/CourseAdmin/CourseForm.jsx
institutionFrontend/src/pages/CourseAdmin/Courses.jsx
institutionFrontend/src/pages/CourseAdmin/LessonsPage.jsx
institutionFrontend/src/pages/CourseAdmin/Programmes.jsx
institutionFrontend/src/pages/admin/ShopeAdmin.jsx
institutionFrontend/src/pages/user/userProfile.jsx

Updation Cleared 
1 : -  apply conditions for image only on profile image 
2 :-  Bread Crumps on the Course Admin Side 
3 :- Modal Confirmation for block and unblock 
4 :- Home Button ( on the navbar) issue

Updation Cleared 

---

institutionFrontend/src/component/Modals/ConfirmModal.jsx
institutionFrontend/src/component/Tables/DataTable.jsx
institutionFrontend/src/pages/instructor/InstructorClassRoom.jsx
institutionFrontend/src/pages/user/ClassRoom.jsx

…m, handled duplicate student. by Anaz

#120 remove student implemented for instructor, modal used for confirm, handled duplicate student. by Anaz

---

institutionFrontend/src/component/MyCourseSection/CustomDatePicker.jsx
institutionFrontend/src/component/MyCourseSection/MainSection.jsx
institutionFrontend/src/component/MyCourseSection/TabPanel.jsx
institutionFrontend/src/component/MyCourseSection/VideoPage.jsx
institutionFrontend/src/services/user/SessionVideos.jsx

connected  session video by saeed

#132 connected  session video by saeed

---

institutionFrontend/src/Context/ProductContext.jsx
institutionFrontend/src/component/Forms/ProductDetailFormFields.jsx
institutionFrontend/src/component/Modals/ImageCrudModal.jsx
institutionFrontend/src/component/Tables/ProductDetailTable.jsx
institutionFrontend/src/pages/ShopAdmin/FormActionButton.jsx
institutionFrontend/src/pages/ShopAdmin/ProductDetails.jsx
institutionFrontend/src/pages/ShopAdmin/ProductDetailsForm.jsx
institutionFrontend/src/routes/ShopAdmin/shopAdminRoutes.jsx
institutionFrontend/src/services/shopAdmin/productImageServices.js
institutionFrontend/src/services/user/ProductServices.jsx

completed img crud modal and and its crud operations

completed img crud modal and and its crud operations 

---

institutionFrontend/src/component/Button/CounterButtons.jsx
institutionFrontend/src/component/Card/CartItems.jsx
institutionFrontend/src/component/Card/CartSumary.jsx
institutionFrontend/src/component/Card/CheckourSummary.jsx
institutionFrontend/src/component/Card/Checkout.jsx
institutionFrontend/src/component/Cart/CartComponent.jsx
institutionFrontend/src/component/Drawer/AddressDrawer.jsx
institutionFrontend/src/component/ErrorPages/EmptyCart.jsx
institutionFrontend/src/component/PaymentDetails/Address.jsx
institutionFrontend/src/component/PaymentDetails/AddressForm.jsx
institutionFrontend/src/component/Products/ProductMainDetail.jsx
institutionFrontend/src/component/StyledComponents/Animations.jsx
institutionFrontend/src/pages/user/ecommerce/Checkout.jsx
institutionFrontend/src/pages/user/ecommerce/HistoryOfOrders.jsx
institutionFrontend/src/pages/user/ecommerce/ProductDetailPage.jsx
institutionFrontend/src/routes/user/UserRoutes.jsx
institutionFrontend/src/services/PinCode/PinCode.jsx
institutionFrontend/src/services/payments/ProductPayment.jsx
institutionFrontend/src/services/user/Address.jsx
institutionFrontend/src/services/user/ecommerce/CartServices.jsx
institutionFrontend/src/services/user/ecommerce/Order.jsx

create order ui both detail page and cart

created order for product

---

institutionFrontend/src/component/Button/CategoryButton.jsx
institutionFrontend/src/component/Drawer/ProductFilter.jsx
institutionFrontend/src/component/Forms/ProductFormFields.jsx
institutionFrontend/src/component/Forms/SubCategoryFormFields.jsx
institutionFrontend/src/component/StyledComponents/StyledProductComponents.jsx
institutionFrontend/src/component/Tables/ProductTable.jsx
institutionFrontend/src/component/Tables/SubCategoryTable.jsx
institutionFrontend/src/layout/ShopAdmin/ShopAdminSideBar.jsx
institutionFrontend/src/pages/ShopAdmin/ProductForm.jsx
institutionFrontend/src/pages/ShopAdmin/Products.jsx
institutionFrontend/src/pages/ShopAdmin/SubCategories.jsx
institutionFrontend/src/pages/ShopAdmin/SubCategoryForm.jsx
institutionFrontend/src/pages/user/ecommerce/ProductsList.jsx
institutionFrontend/src/routes/ShopAdmin/shopAdminRoutes.jsx
institutionFrontend/src/services/shopAdmin/categoryServices.js
institutionFrontend/src/services/user/ProductServices.jsx

162 completed product subcategory crud brud crumbs created Category Button Component

162 completed product subcategory crud brud crumbs created Category Button Component 
